repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args: [--disable=all, --enable=unused-import,trailing-whitespace, "C:/Users/Ranganath/THIS/django/temp/venv/Scripts/pylint.exe"]
