repos:
# - repo: https://github.com/pre-commit/pre-commit-hooks
#   rev: v4.5.0
#   hooks:
#   - id: check-yaml
#   - id: end-of-file-fixer
#   - id: trailing-whitespace
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: venv\Scripts\pylint.exe
    language: system
    types: [python]
    args: [--ignore-patterns=venv]
